[build]
cmd = "echo \"build\""
full_bin = "CGO_ENABLED=1 go build -gcflags \"all=-N -l\" -o ./bin/server ./main.go && dlv exec --continue --listen=:40000 --headless=true --api-version=2 --accept-multiclient --log ./bin/server config config/config.yml"
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
exclude_dir = ["assets", "tmp", "vendor", "bin"]

[log]
level = "debug"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"